# TEST ENVIRONMENT (Local H2 Database)

## Application server port
server.port=8081

## H2 Database configuration
spring.datasource.url=jdbc:h2:mem:db_invflo
spring.datasource.username=popehiflo
spring.datasource.password=invflo

## JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=true

## habilitar consola de H2
spring.h2.console.enabled = true
