spring.application.name=invflo-backend

# Set the active profile
spring.profiles.active=dev

# Banner
application.title= InvFlo - eCommerce
application.version= 1.0
application.author= popehiflo
application.author.name= Pool Hijuela
application.author.email= popehiflo@gmail.com
application.description= InvFlo Simple eCommerce
application.url=https://popehiflo.github.io

